export const goals = [
  "OBIETTIVO CAPITOLO NUOVA ERA GENOVA Che tutti i giorni della settimana ci sia una casa in cui gli uomini del Capitolo Nuova Era possano recitare assieme 1 ora di Daimoku per Kosen Rufu",
  "Che tutti i giorni della settimana ci sia una casa in cui gli uomini del Capitolo Nuova Era possano recitare assieme 1 ora di Daimoku per Kosen Rufu",
  "Esperienza sul lavoro",
  "La crescita del capitolo Saragozza affinche ogni uomo diventi felive e crei successori...",
  "Alla fine del corso vorrei provare la stessa determinazione di Sensei Ikeda",
  "Sostenere tutto  il Capitolo Visconti  Milano crescita di uomini,e giovani uomini che tutti  i partecipanti  realizzano grandi esperienze di fede",
  "Smettere di fumare e prendermi cura della mia salute per rispettare la sacralità della mia vita. ",
  "Crescere sempre di più nella azienda dove lavoro, coltivare sempre più legami di amicizia con tutti i colleghi e le persone che si interfacciano con la mia vita, puntando al dialogo valoroso e alla felicità di ogni individuo ❤️",
  "Smettere di fumare. Prendermi cura della mia salute e avere rispetto della sacralità della vita mia e altrui.",
  "Smettere di fumare. Avere cura della mia salute e rispettare la sacralità della mia vita.",
  "Smettere di fumare. Rispettare la sacralità della mia vita. ",
  "Crescita del capitolo signoria con 1 giovane nuovo per ogni gruppo.. ",
  "Riportare una grande vittoria al nostro maestro ",
  "Rivitalizzare tutta la mia pratica e diventare campione di incoraggiamento e vitalità! Terminare la mia carriera in modo luminoso e mostrarmi grato e generoso verso tutti.",
  " 2 nuovi membri giovani e realizzare gli scopi dei gruppi Liguria 3",
  "La felicità di tutti i partecipanti al corso e la determinazione di realizzare una crescita dei giovani uomini tornati nelle nostre regioni ",
  "Crescita del Capitolo Oliveta con emergere di nuovi successori nei gruppi, settore e nel capitolo. Consegna entro il 31/12/2025 di 30 Gohonzon. Crescita lavorativa e di stipendio, diventando manager nella mia azienda di un nuovo ufficio composto da 10 giovani a cui farò shakubuku ed inizieranno a praticare. ",
  "Carriera lavorativa, livello superiore a lavoro.",
  "Con alla base la determinazione e volontà di realizzare gli Obiettivi 2025 per la felicità dei membri alcuni punti sintetici per me importanti: 1) Diventare un buon Discepolo di Sensei; 2) Continuare a trasmettere alle future generazioni la grandezza e lo Spirito di Sensei, (come da mia domanda a un corso in Giappone e risposta del Vice direttore Ishiguro; 3) Diventare un ottimo psicologo a sostegno dei genitori e dell'età evolutiva",
  "Tutti i partecipanti siano felici e realizzino grandi esperienze ",
  "Resettare e ripartire... sempre meglio ",
  "Sostenere tutte le persone del Capitolo Savona Ovest  e costruire un profondo legame con ognuno di loro.\nSostenere il settore Valbormida perchè diventi un Capitolo\nimaparare a volermi veramente bene ",
  "Una maggiore partecipazione attiva di tutto il gruppo uomini, e che aumenti il loro desiderio di studiare e approfondire la conoscenza di qs buddismo per poterlo applicare alla propria vita e diventare felici",
  "acquisite e condividere il potere assoluto del Gohonzon per far progredire più velocemente kosen-rufu nella mia zona",
  "ACQUISIRE E CONDIVIDERE LA CONVINZIONE ASSOLUTA NEL POTERE DELLA FEDE PER FAR PROGREDIRE KOSEN RUFU NELLA MIA ZONA ",
  "Vincere sulle mie debolezze e sfiducia per Kosen Rufu \nFar crescere un uomo nella fede entro il 3 maggio.",
];
